version: 0.3

project:
 name: "rxclient"
 apt:
   sources:
     - "rpm ftp://server/pub ALTLinux/Sisyphus/x86_64 classic"
     - "rpm ftp://server/pub ALTLinux/Sisyphus/noarch classic"
     #- rpm http://ftp.altlinux.org/pub/distributions/ALTLinux Sisyphus/x86_64 classic
     #- rpm http://ftp.altlinux.org/pub/distributions/ALTLinux Sisyphus/noarch classic

 groups:
   rx:
     nodes:
       rxclient:
         context: "rxclient-$BUILD_ID"
         image: x64.sisyphus-rxclient
         start_command: start-rx-client.sh
         hostname: "rxclient-$BUILD_ID"
         environment:
           - "SERVICE_NAME=$RXCLIENT_NAME"
           - "SERVICE_TAGS=rxclient,build-$BUILD_ID"
         ports:
           - "$CI_BUILD_ID:22"
         volumes:
          - "./rxclient-config:/home/guest/.nx/config"
         copy:
           - "rx-test.list:/etc/apt/sources.list.d/"
           - "03-logging.conf:/etc/rx-etersoft/node.conf.d/"
           - "guest:/home/guest/"
           - "[0400]guest.sudo:/etc/sudoers.d/guest"
           
         before_command: 
           - epm repolist && epm update
           - epm i --auto rxclient
           - chown -R guest:guest /home/guest/.nx /home/guest/.opennx /home/guest/Desktop
           - chown root:root /etc/sudoers.d/guest

       rxserver:
         context: "rxclient-rxserver-$BUILD_ID"
         image: x64.sisyphus-rxserver
         start_command: start-rx.sh
         hostname: "rx-server-$BUILD_ID"
         environment:
           - "SERVICE_NAME=$RXSERVER_NAME"
           - "SERVICE_TAGS=rxclient,build-$BUILD_ID"
         copy:
           - "03-logging.conf:/etc/rx-etersoft/node.conf.d/"
           - "guest.sudo:/etc/sudoers.d/guest"
         before_command: 
           - chown root:root /etc/sudoers.d/guest           
         ports:
           - "$BUILD_ID:22"
